[package]
name = "webserver"
version = "0.0.1"
edition = "2024"
authors = ["NolanV <git@nolan.contact>"]

[dependencies]
actix-web = "4.9.0"
actix-files = "0.6.6"
maud = { version = "0.27.0", features = ["actix-web"] }
serde = { version = "1.0.218", features = ["derive"] }
